# Generated by Django 6.0 on 2026-01-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_unique_name_alter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='unique_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
